"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Bot, BookOpen, CheckCircle2, CreditCard, DatabaseZap, KeyRound, LoaderCircle, Plus, RefreshCw, Save, ShieldCheck, SlidersHorizontal, Trash2, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input, Textarea } from "@/components/ui/input";
import type { PlatformAIModel, PlatformAIProvider, PlatformOAuthIntegration, PlatformStripeConfiguration } from "@/lib/server/platform-admin";
import type { FeatureKey, SubscriptionPlan } from "@/types";

type Overview = { providers: PlatformAIProvider[]; models: PlatformAIModel[]; oauth: PlatformOAuthIntegration[]; stripe: PlatformStripeConfiguration; plans: SubscriptionPlan[] };
type Tab = "providers" | "models" | "oauth" | "stripe" | "plans" | "docs";

const tabs: Array<{ id: Tab; label: string; icon: typeof Bot }> = [
  { id: "providers", label: "Fournisseurs IA", icon: Bot },
  { id: "models", label: "Modèles", icon: SlidersHorizontal },
  { id: "oauth", label: "Connexions OAuth", icon: KeyRound },
  { id: "stripe", label: "Paiement / Stripe", icon: CreditCard },
  { id: "plans", label: "Abonnements", icon: WalletCards },
  { id: "docs", label: "Documentation", icon: BookOpen },
];

async function postAction(payload: Record<string, unknown>) {
  const response = await fetch("/api/admin/platform", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
  const result = await response.json().catch(() => ({})) as { error?: string; count?: number; accountId?: string };
  if (!response.ok) throw new Error(result.error ?? "Action impossible");
  return result;
}

export function PlatformAdminPage() {
  const [overview, setOverview] = useState<Overview>();
  const [tab, setTab] = useState<Tab>("providers");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    const response = await fetch("/api/admin/platform", { cache: "no-store" });
    const result = await response.json() as Overview & { error?: string };
    if (!response.ok) throw new Error(result.error ?? "Configuration indisponible");
    setOverview(result);
  }, []);

  useEffect(() => {
    let active = true;
    fetch("/api/admin/platform", { cache: "no-store" })
      .then(async (response) => {
        const result = await response.json() as Overview & { error?: string };
        if (!response.ok) throw new Error(result.error ?? "Configuration indisponible");
        return result;
      })
      .then((result) => { if (active) setOverview(result); })
      .catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "Accès refusé"); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);

  if (loading) return <main className="flex min-h-screen items-center justify-center"><LoaderCircle className="size-8 animate-spin text-primary" /></main>;
  if (error || !overview) return <main className="flex min-h-screen items-center justify-center p-6"><Card><CardContent className="p-8 text-center"><ShieldCheck className="mx-auto size-9 text-rose-500" /><h1 className="mt-3 text-xl font-semibold">Console indisponible</h1><p className="mt-2 text-sm text-muted-foreground">{error}</p><Link href="/admin" className="mt-5 inline-flex text-sm text-primary">Retour à l’administration</Link></CardContent></Card></main>;

  return <main className="min-h-screen bg-muted/20">
    <header className="sticky top-0 z-30 flex min-h-16 items-center gap-3 border-b bg-background/95 px-3 py-3 backdrop-blur sm:px-6"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-violet-500/10 text-violet-500"><DatabaseZap className="size-5" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">Configuration plateforme</p><p className="hidden text-[11px] text-muted-foreground sm:block">Secrets chiffrés, catalogue dynamique et audit</p></div><Button variant="ghost" size="sm" onClick={() => void load()}><RefreshCw className="size-4" /><span className="hidden sm:inline">Actualiser</span></Button><Link href="/admin" className="text-xs text-muted-foreground hover:text-foreground sm:text-sm">Comptes</Link></header>
    <div className="mx-auto max-w-[1500px] p-3 sm:p-6 lg:p-8">
      <div className="scrollbar-none mb-6 flex gap-2 overflow-x-auto pb-2">{tabs.map((item) => <Button key={item.id} className="shrink-0" variant={tab === item.id ? "secondary" : "ghost"} onClick={() => setTab(item.id)}><item.icon className="size-4" />{item.label}</Button>)}</div>
      {tab === "providers" && <ProvidersPanel items={overview.providers} onChanged={load} />}
      {tab === "models" && <ModelsPanel items={overview.models} providers={overview.providers} onChanged={load} />}
      {tab === "oauth" && <OAuthPanel items={overview.oauth} onChanged={load} />}
      {tab === "stripe" && <StripePanel value={overview.stripe} onChanged={load} />}
      {tab === "plans" && <PlansPanel items={overview.plans} onChanged={load} />}
      {tab === "docs" && <DocumentationPanel />}
    </div>
  </main>;
}

function StatusBadge({ status }: { status: PlatformAIProvider["verificationStatus"] }) {
  return <Badge className={status === "valid" ? "bg-emerald-500/10 text-emerald-500" : status === "invalid" ? "bg-rose-500/10 text-rose-500" : "bg-muted text-muted-foreground"}>{status === "valid" ? "Vérifié" : status === "invalid" ? "Erreur" : "Non testé"}</Badge>;
}

function ProvidersPanel({ items, onChanged }: { items: PlatformAIProvider[]; onChanged: () => Promise<void> }) {
  const [selectedId, setSelectedId] = useState(items[0]?.id ?? "new");
  const selected = items.find((item) => item.id === selectedId);
  const [form, setForm] = useState<Record<string, string>>(() => selected ? providerForm(selected) : emptyProviderForm());
  const [busy, setBusy] = useState("");
  const selectProvider = (id: string) => { setSelectedId(id); const item = items.find((provider) => provider.id === id); setForm(item ? providerForm(item) : emptyProviderForm()); };

  const run = async (payload: Record<string, unknown>, message: string) => { setBusy(String(payload.action)); try { await postAction(payload); await onChanged(); toast.success(message); } catch (error) { toast.error(error instanceof Error ? error.message : "Action impossible"); } finally { setBusy(""); } };
  return <MasterDetail title="Fournisseurs IA" description="La clé globale sert de secours lorsque l’entreprise n’a pas sa propre clé." items={items.map((item) => ({ id: item.id, title: item.name, subtitle: item.kind, status: item.verificationStatus }))} selectedId={selectedId} onSelect={selectProvider} onNew={() => selectProvider("new")}>
    <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); void run({ action: "save_provider", ...(selected ? { id: selected.id } : {}), ...form }, "Fournisseur enregistré"); }}>
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Nom"><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></Field><Field label="Identifiant"><Input value={form.slug} disabled={Boolean(selected)} onChange={(event) => setForm({ ...form, slug: event.target.value.toLowerCase() })} required /></Field></div>
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Type"><select className="h-10 w-full rounded-xl border bg-background px-3 text-sm" value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value })}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="openai_compatible">Compatible OpenAI</option></select></Field><Field label="Statut"><select className="h-10 w-full rounded-xl border bg-background px-3 text-sm" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="active">Actif</option><option value="inactive">Inactif</option></select></Field></div>
      <Field label="URL de base"><Input type="url" value={form.baseUrl} onChange={(event) => setForm({ ...form, baseUrl: event.target.value })} placeholder="https://api.example.com/v1" /></Field>
      <Field label={selected?.hasApiKey ? `Nouvelle clé API (${selected.secretHint})` : "Clé API"}><Input type="password" autoComplete="new-password" value={form.apiKey} onChange={(event) => setForm({ ...form, apiKey: event.target.value })} placeholder={selected?.hasApiKey ? "Laisser vide pour conserver" : "sk-…"} /></Field>
      <Field label="Notes internes"><Textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></Field>
      {selected?.lastError && <p className="rounded-xl border border-rose-500/20 bg-rose-500/5 p-3 text-xs text-rose-500">{selected.lastError}</p>}
      <div className="flex flex-wrap gap-2"><Button type="submit" disabled={Boolean(busy)}>{busy === "save_provider" ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}Enregistrer</Button>{selected && <><Button type="button" variant="outline" disabled={Boolean(busy) || !selected.hasApiKey} onClick={() => void run({ action: "test_provider", id: selected.id }, "Connexion valide")}><CheckCircle2 className="size-4" />Tester</Button><Button type="button" variant="outline" disabled={Boolean(busy) || !selected.hasApiKey} onClick={() => void run({ action: "sync_models", providerId: selected.id }, "Modèles synchronisés")}><RefreshCw className="size-4" />Synchroniser</Button><Button type="button" variant="ghost" onClick={() => { if (confirm("Supprimer ce fournisseur et ses modèles ?")) void run({ action: "delete_provider", id: selected.id }, "Fournisseur supprimé"); }}><Trash2 className="size-4 text-rose-500" /></Button></>}</div>
    </form>
  </MasterDetail>;
}

function providerForm(item: PlatformAIProvider) { return { slug: item.slug, name: item.name, kind: item.kind, baseUrl: item.baseUrl ?? "", status: item.status, notes: item.notes, apiKey: "" }; }
function emptyProviderForm() { return { slug: "", name: "", kind: "openai_compatible", baseUrl: "", status: "inactive", notes: "", apiKey: "" }; }

function ModelsPanel({ items, providers, onChanged }: { items: PlatformAIModel[]; providers: PlatformAIProvider[]; onChanged: () => Promise<void> }) {
  const [selectedId, setSelectedId] = useState(items[0]?.id ?? "new");
  const selected = items.find((item) => item.id === selectedId);
  const [form, setForm] = useState(() => modelForm(selected, providers[0]?.id));
  const [busy, setBusy] = useState(false);
  const selectModel = (id: string) => { setSelectedId(id); setForm(modelForm(items.find((item) => item.id === id), providers[0]?.id)); };
  const save = async () => { setBusy(true); try { await postAction({ action: "save_model", ...(selected ? { id: selected.id } : {}), ...form, inputNanoUsdPerMillion: Math.round(Number(form.inputUsd) * 1e9), cachedInputNanoUsdPerMillion: form.cachedInputUsd === "" ? undefined : Math.round(Number(form.cachedInputUsd) * 1e9), outputNanoUsdPerMillion: Math.round(Number(form.outputUsd) * 1e9), marginBasisPoints: Math.round(Number(form.marginPercent) * 100), contextWindowTokens: numberOrUndefined(form.contextWindowTokens), maxOutputTokens: numberOrUndefined(form.maxOutputTokens), requestTokenLimit: numberOrUndefined(form.requestTokenLimit), capabilities: splitList(form.capabilities) }); await onChanged(); toast.success("Modèle enregistré et tarif versionné"); } catch (error) { toast.error(error instanceof Error ? error.message : "Enregistrement impossible"); } finally { setBusy(false); } };
  return <MasterDetail title="Catalogue de modèles" description="Les prix sont en USD par million de tokens. Chaque changement crée un nouveau tarif actif." items={items.map((item) => ({ id: item.id, title: item.displayName, subtitle: `${item.providerName} · ${item.modelId}`, status: item.enabled ? "valid" : "never" }))} selectedId={selectedId} onSelect={selectModel} onNew={() => selectModel("new")}>
    <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Fournisseur"><select className="h-10 w-full rounded-xl border bg-background px-3 text-sm" value={form.providerId} onChange={(event) => setForm({ ...form, providerId: event.target.value })}>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></Field><Field label="ID du modèle"><Input value={form.modelId} onChange={(event) => setForm({ ...form, modelId: event.target.value })} /></Field><Field label="Nom affiché"><Input value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} /></Field><Field label="Capacités"><Input value={form.capabilities} onChange={(event) => setForm({ ...form, capabilities: event.target.value })} placeholder="text, vision, tools" /></Field></div>
      <Field label="Description"><Textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Entrée $ / 1M"><Input type="number" step="0.000001" min="0" value={form.inputUsd} onChange={(event) => setForm({ ...form, inputUsd: event.target.value })} /></Field><Field label="Cache $ / 1M"><Input type="number" step="0.000001" min="0" value={form.cachedInputUsd} onChange={(event) => setForm({ ...form, cachedInputUsd: event.target.value })} /></Field><Field label="Sortie $ / 1M"><Input type="number" step="0.000001" min="0" value={form.outputUsd} onChange={(event) => setForm({ ...form, outputUsd: event.target.value })} /></Field><Field label="Marge %"><Input type="number" step="0.01" min="0" value={form.marginPercent} onChange={(event) => setForm({ ...form, marginPercent: event.target.value })} /></Field></div>
      <div className="grid gap-3 sm:grid-cols-3"><Field label="Contexte max"><Input type="number" value={form.contextWindowTokens} onChange={(event) => setForm({ ...form, contextWindowTokens: event.target.value })} /></Field><Field label="Sortie max"><Input type="number" value={form.maxOutputTokens} onChange={(event) => setForm({ ...form, maxOutputTokens: event.target.value })} /></Field><Field label="Limite / requête"><Input type="number" value={form.requestTokenLimit} onChange={(event) => setForm({ ...form, requestTokenLimit: event.target.value })} /></Field></div>
      <div className="grid gap-2 sm:grid-cols-4"><Check label="Actif" value={form.enabled} onChange={(value) => setForm({ ...form, enabled: value })} /><Check label="Visible" value={form.userVisible} onChange={(value) => setForm({ ...form, userVisible: value })} /><Check label="Premium" value={form.premium} onChange={(value) => setForm({ ...form, premium: value })} /><Check label="Par défaut" value={form.isDefault} onChange={(value) => setForm({ ...form, isDefault: value })} /></div>
      <div className="flex gap-2"><Button disabled={busy || !form.modelId || !form.providerId} onClick={() => void save()}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}Enregistrer</Button>{selected && <Button variant="ghost" onClick={() => { if (confirm("Supprimer ce modèle ?")) void postAction({ action: "delete_model", id: selected.id }).then(onChanged).then(() => toast.success("Modèle supprimé")).catch((error) => toast.error(error.message)); }}><Trash2 className="size-4 text-rose-500" /></Button>}</div>
    </div>
  </MasterDetail>;
}

function modelForm(item?: PlatformAIModel, providerId = "") { return { providerId: item?.providerId ?? providerId, modelId: item?.modelId ?? "", displayName: item?.displayName ?? "", description: item?.description ?? "", enabled: item?.enabled ?? true, userVisible: item?.userVisible ?? true, isDefault: item?.isDefault ?? false, premium: item?.premium ?? false, capabilities: (item?.capabilities ?? ["text"]).join(", "), inputUsd: String((item?.inputNanoUsdPerMillion ?? 0) / 1e9), cachedInputUsd: item?.cachedInputNanoUsdPerMillion === undefined ? "" : String(item.cachedInputNanoUsdPerMillion / 1e9), outputUsd: String((item?.outputNanoUsdPerMillion ?? 0) / 1e9), marginPercent: String((item?.marginBasisPoints ?? 0) / 100), contextWindowTokens: String(item?.contextWindowTokens ?? ""), maxOutputTokens: String(item?.maxOutputTokens ?? ""), requestTokenLimit: String(item?.requestTokenLimit ?? ""), sortOrder: item?.sortOrder ?? 0 }; }

function OAuthPanel({ items, onChanged }: { items: PlatformOAuthIntegration[]; onChanged: () => Promise<void> }) {
  const [selectedId, setSelectedId] = useState(items[0]?.id ?? "new"); const selected = items.find((item) => item.id === selectedId); const [form, setForm] = useState(() => oauthForm(selected)); const [busy, setBusy] = useState(""); const selectOAuth = (id: string) => { setSelectedId(id); setForm(oauthForm(items.find((item) => item.id === id))); };
  const run = async (payload: Record<string, unknown>, message: string) => { setBusy(String(payload.action)); try { await postAction(payload); await onChanged(); toast.success(message); } catch (error) { toast.error(error instanceof Error ? error.message : "Action impossible"); } finally { setBusy(""); } };
  return <MasterDetail title="Connexions OAuth" description="Le test valide les champs et l’accessibilité des endpoints. La connexion utilisateur confirme ensuite réellement les autorisations." items={items.map((item) => ({ id: item.id, title: item.name, subtitle: item.provider, status: item.verificationStatus }))} selectedId={selectedId} onSelect={selectOAuth} onNew={() => selectOAuth("new")}>
    <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); void run({ action: "save_oauth", ...(selected ? { id: selected.id } : {}), ...form, scopes: splitList(form.scopes), configuration: {} }, "Connexion OAuth enregistrée"); }}><div className="grid gap-3 sm:grid-cols-2"><Field label="Nom"><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></Field><Field label="Identifiant"><Input value={form.slug} disabled={Boolean(selected)} onChange={(event) => setForm({ ...form, slug: event.target.value.toLowerCase() })} required /></Field><Field label="Fournisseur"><Input value={form.provider} onChange={(event) => setForm({ ...form, provider: event.target.value })} required /></Field><Field label="Statut"><select className="h-10 w-full rounded-xl border bg-background px-3 text-sm" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="active">Actif</option><option value="inactive">Inactif</option></select></Field></div>
      <Field label="Client ID"><Input value={form.clientId} onChange={(event) => setForm({ ...form, clientId: event.target.value })} /></Field><Field label={selected?.hasClientSecret ? `Nouveau Client Secret (${selected.secretHint})` : "Client Secret"}><Input type="password" autoComplete="new-password" value={form.clientSecret} onChange={(event) => setForm({ ...form, clientSecret: event.target.value })} placeholder={selected?.hasClientSecret ? "Laisser vide pour conserver" : "Secret OAuth"} /></Field>
      <Field label="Redirect URI"><Input type="url" value={form.redirectUri} onChange={(event) => setForm({ ...form, redirectUri: event.target.value })} /></Field><Field label="URL d’autorisation"><Input type="url" value={form.authorizationUrl} onChange={(event) => setForm({ ...form, authorizationUrl: event.target.value })} /></Field><Field label="URL de token"><Input type="url" value={form.tokenUrl} onChange={(event) => setForm({ ...form, tokenUrl: event.target.value })} /></Field><Field label="Scopes, séparés par des virgules"><Textarea value={form.scopes} onChange={(event) => setForm({ ...form, scopes: event.target.value })} /></Field>
      {selected?.lastError && <p className="rounded-xl border border-rose-500/20 bg-rose-500/5 p-3 text-xs text-rose-500">{selected.lastError}</p>}
      <div className="flex gap-2"><Button type="submit" disabled={Boolean(busy)}><Save className="size-4" />Enregistrer</Button>{selected && <><Button type="button" variant="outline" disabled={Boolean(busy)} onClick={() => void run({ action: "test_oauth", id: selected.id }, "Configuration OAuth valide")}><CheckCircle2 className="size-4" />Vérifier</Button><Button type="button" variant="ghost" onClick={() => { if (confirm("Supprimer cette intégration ?")) void run({ action: "delete_oauth", id: selected.id }, "Intégration supprimée"); }}><Trash2 className="size-4 text-rose-500" /></Button></>}</div>
    </form>
  </MasterDetail>;
}

function oauthForm(item?: PlatformOAuthIntegration): Record<string, string> { return { slug: item?.slug ?? "", provider: item?.provider ?? "", name: item?.name ?? "", clientId: item?.clientId ?? "", clientSecret: "", authorizationUrl: item?.authorizationUrl ?? "", tokenUrl: item?.tokenUrl ?? "", redirectUri: item?.redirectUri ?? "", scopes: (item?.scopes ?? []).join(", "), status: item?.status ?? "inactive" }; }

function StripePanel({ value, onChanged }: { value: PlatformStripeConfiguration; onChanged: () => Promise<void> }) {
  const [form, setForm] = useState({ mode: value.mode, status: value.status, publishableKey: value.publishableKey, secretKey: "", webhookSecret: "" }); const [busy, setBusy] = useState("");
  const run = async (payload: Record<string, unknown>, message: string) => { setBusy(String(payload.action)); try { const result = await postAction(payload); await onChanged(); toast.success(result.accountId ? `${message} · ${result.accountId}` : message); } catch (error) { toast.error(error instanceof Error ? error.message : "Action impossible"); } finally { setBusy(""); } };
  return <div className="grid gap-5 xl:grid-cols-[1fr_360px]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CreditCard className="size-5 text-violet-500" />Configuration Stripe</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); void run({ action: "save_stripe", ...form }, "Stripe enregistré"); }}><div className="grid gap-3 sm:grid-cols-2"><Field label="Mode"><select className="h-10 w-full rounded-xl border bg-background px-3 text-sm" value={form.mode} onChange={(event) => setForm({ ...form, mode: event.target.value as "test" | "production" })}><option value="test">Test</option><option value="production">Production</option></select></Field><Field label="Statut"><select className="h-10 w-full rounded-xl border bg-background px-3 text-sm" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as "active" | "inactive" })}><option value="active">Actif</option><option value="inactive">Inactif</option></select></Field></div><Field label="Clé publique"><Input value={form.publishableKey} onChange={(event) => setForm({ ...form, publishableKey: event.target.value })} placeholder="pk_test_…" /></Field><Field label={value.hasSecretKey ? `Nouvelle clé secrète (${value.secretKeyHint})` : "Clé secrète"}><Input type="password" autoComplete="new-password" value={form.secretKey} onChange={(event) => setForm({ ...form, secretKey: event.target.value })} placeholder="sk_test_… ou rk_live_…" /></Field><Field label={value.hasWebhookSecret ? `Nouveau secret webhook (${value.webhookSecretHint})` : "Secret webhook"}><Input type="password" autoComplete="new-password" value={form.webhookSecret} onChange={(event) => setForm({ ...form, webhookSecret: event.target.value })} placeholder="whsec_…" /></Field>{value.lastError && <p className="rounded-xl border border-rose-500/20 bg-rose-500/5 p-3 text-xs text-rose-500">{value.lastError}</p>}<div className="flex gap-2"><Button type="submit" disabled={Boolean(busy)}><Save className="size-4" />Enregistrer</Button><Button type="button" variant="outline" disabled={Boolean(busy) || !value.hasSecretKey} onClick={() => void run({ action: "test_stripe" }, "Compte Stripe vérifié")}><CheckCircle2 className="size-4" />Tester</Button></div></form></CardContent></Card><Card className="h-fit"><CardHeader><CardTitle>État</CardTitle></CardHeader><CardContent className="space-y-3"><StatusBadge status={value.verificationStatus} /><p className="text-sm">Mode <strong>{value.mode}</strong></p><p className="text-xs leading-5 text-muted-foreground">Le webhook utilise immédiatement le secret stocké en base. L’URL à déclarer dans Stripe est <code>/api/billing/webhook</code>.</p><p className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-xs text-amber-600">En production, utilisez de préférence une clé restreinte Stripe plutôt qu’une clé secrète complète.</p></CardContent></Card></div>;
}

function PlansPanel({ items, onChanged }: { items: SubscriptionPlan[]; onChanged: () => Promise<void> }) {
  const [selectedId, setSelectedId] = useState(items[0]?.id ?? "new"); const selected = items.find((item) => item.id === selectedId); const [form, setForm] = useState(() => planForm(selected)); const [busy, setBusy] = useState(false); const selectPlan = (id: string) => { setSelectedId(id); setForm(planForm(items.find((item) => item.id === id))); };
  const save = async () => { setBusy(true); try { await postAction({ action: "save_plan", ...form, monthlyPriceCents: Number(form.monthlyPriceCents), annualPriceCents: Number(form.annualPriceCents), monthlyTokenLimit: Number(form.monthlyTokenLimit), dailyTokenLimit: Number(form.dailyTokenLimit), minuteRequestLimit: Number(form.minuteRequestLimit), maxAgents: Number(form.maxAgents), maxMembers: Number(form.maxMembers), maxAutomations: Number(form.maxAutomations), storageLimitMb: Number(form.storageLimitMb), contextLimitTokens: Number(form.contextLimitTokens), maxModels: Number(form.maxModels), sortOrder: Number(form.sortOrder), features: splitList(form.features) as FeatureKey[], badges: splitList(form.badges), includedFeatures: splitList(form.includedFeatures), exclusiveFeatures: splitList(form.exclusiveFeatures), limits: {} }); await onChanged(); toast.success("Offre mise à jour sur la tarification"); } catch (error) { toast.error(error instanceof Error ? error.message : "Enregistrement impossible"); } finally { setBusy(false); } };
  return <MasterDetail title="Offres d’abonnement" description="Les changements sont lus directement par la tarification, les quotas et Stripe." items={items.map((item) => ({ id: item.id, title: item.name, subtitle: item.quoteOnly ? "Sur devis" : `${((item.monthlyPriceCents ?? 0) / 100).toLocaleString("fr-FR")} ${item.currency?.toUpperCase()}/mois`, status: item.active === false ? "never" : "valid" }))} selectedId={selectedId} onSelect={selectPlan} onNew={() => selectPlan("new")}>
    <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Identifiant"><Input value={form.id} disabled={Boolean(selected)} onChange={(event) => setForm({ ...form, id: event.target.value.toLowerCase() })} /></Field><Field label="Nom"><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field></div><Field label="Description"><Textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field>
      <div className="grid gap-3 sm:grid-cols-3"><Field label="Prix mensuel (centimes)"><Input type="number" value={form.monthlyPriceCents} onChange={(event) => setForm({ ...form, monthlyPriceCents: event.target.value })} /></Field><Field label="Prix annuel (centimes)"><Input type="number" value={form.annualPriceCents} onChange={(event) => setForm({ ...form, annualPriceCents: event.target.value })} /></Field><Field label="Devise"><Input value={form.currency} onChange={(event) => setForm({ ...form, currency: event.target.value.toLowerCase() })} /></Field></div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><NumberField label="Tokens / mois" name="monthlyTokenLimit" form={form} setForm={setForm} /><NumberField label="Tokens / jour" name="dailyTokenLimit" form={form} setForm={setForm} /><NumberField label="Requêtes / minute" name="minuteRequestLimit" form={form} setForm={setForm} /><NumberField label="Agents" name="maxAgents" form={form} setForm={setForm} /><NumberField label="Automatisations" name="maxAutomations" form={form} setForm={setForm} /><NumberField label="Membres" name="maxMembers" form={form} setForm={setForm} /><NumberField label="Stockage Mo" name="storageLimitMb" form={form} setForm={setForm} /><NumberField label="Contexte tokens" name="contextLimitTokens" form={form} setForm={setForm} /><NumberField label="Modèles max" name="maxModels" form={form} setForm={setForm} /><NumberField label="Ordre" name="sortOrder" form={form} setForm={setForm} /></div>
      <div className="grid gap-2 sm:grid-cols-3"><Check label="Actif" value={form.active} onChange={(value) => setForm({ ...form, active: value })} /><Check label="Mis en avant" value={form.highlighted} onChange={(value) => setForm({ ...form, highlighted: value })} /><Check label="Sur devis" value={form.quoteOnly} onChange={(value) => setForm({ ...form, quoteOnly: value })} /><Check label="Modèles premium" value={form.premiumModels} onChange={(value) => setForm({ ...form, premiumModels: value })} /><Check label="Connecteurs" value={form.connectorsEnabled} onChange={(value) => setForm({ ...form, connectorsEnabled: value })} /><Check label="Outils" value={form.toolsEnabled} onChange={(value) => setForm({ ...form, toolsEnabled: value })} /></div>
      <Field label="Fonctionnalités techniques"><Input value={form.features} onChange={(event) => setForm({ ...form, features: event.target.value })} placeholder="assistant, chatbots, goals…" /></Field><Field label="Fonctionnalités affichées"><Textarea value={form.includedFeatures} onChange={(event) => setForm({ ...form, includedFeatures: event.target.value })} /></Field><Field label="Badges"><Input value={form.badges} onChange={(event) => setForm({ ...form, badges: event.target.value })} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Price ID Stripe mensuel"><Input value={form.stripeMonthlyPriceId} onChange={(event) => setForm({ ...form, stripeMonthlyPriceId: event.target.value })} /></Field><Field label="Price ID Stripe annuel"><Input value={form.stripeAnnualPriceId} onChange={(event) => setForm({ ...form, stripeAnnualPriceId: event.target.value })} /></Field></div>
      <div className="flex gap-2"><Button disabled={busy || !form.id || !form.name} onClick={() => void save()}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}Enregistrer</Button>{selected && selected.id !== "free" && <Button variant="ghost" onClick={() => { if (confirm("Supprimer définitivement cette offre ?")) void postAction({ action: "delete_plan", id: selected.id }).then(onChanged).then(() => toast.success("Offre supprimée")).catch((error) => toast.error(error.message)); }}><Trash2 className="size-4 text-rose-500" /></Button>}</div>
    </div>
  </MasterDetail>;
}

function planForm(item?: SubscriptionPlan) { return { id: item?.id ?? "", name: item?.name ?? "", description: item?.description ?? "", monthlyPriceCents: String(item?.monthlyPriceCents ?? 0), annualPriceCents: String(item?.annualPriceCents ?? 0), currency: item?.currency ?? "eur", monthlyTokenLimit: String(item?.monthlyTokenLimit ?? 100000), dailyTokenLimit: String(item?.dailyTokenLimit ?? 25000), minuteRequestLimit: String(item?.minuteRequestLimit ?? 3), maxAgents: String(item?.maxAgents ?? 0), maxMembers: String(item?.maxMembers ?? 1), maxAutomations: String(item?.maxAutomations ?? 0), storageLimitMb: String(item?.storageLimitMb ?? 100), contextLimitTokens: String(item?.contextLimitTokens ?? 32000), maxModels: String(item?.maxModels ?? 1), premiumModels: item?.premiumModels ?? false, connectorsEnabled: item?.connectorsEnabled ?? false, toolsEnabled: item?.toolsEnabled ?? false, features: (item?.features ?? ["assistant"]).join(", "), badges: (item?.badges ?? []).join(", "), includedFeatures: (item?.includedFeatures ?? item?.features ?? []).join(", "), exclusiveFeatures: (item?.exclusiveFeatures ?? []).join(", "), highlighted: item?.highlighted ?? false, quoteOnly: item?.quoteOnly ?? false, sortOrder: String(item?.sortOrder ?? 0), active: item?.active ?? true, stripeMonthlyPriceId: item?.stripeMonthlyPriceId ?? "", stripeAnnualPriceId: item?.stripeAnnualPriceId ?? "" }; }

const docs = [
  { title: "OpenAI", steps: ["Créez un projet dans la plateforme OpenAI.", "Créez une clé API de projet et copiez-la une seule fois.", "Ajoutez OpenAI dans Fournisseurs IA, activez-le puis testez.", "Synchronisez les modèles et renseignez les tarifs officiels."], errors: "401 : clé invalide. 429 : quota ou facturation. 404 : modèle non autorisé.", link: "https://platform.openai.com/api-keys" },
  { title: "Anthropic", steps: ["Créez un compte Claude Console et un espace de travail.", "Ajoutez des crédits puis créez une API Key.", "Renseignez le fournisseur Anthropic avec https://api.anthropic.com.", "Testez puis synchronisez les modèles Claude."], errors: "401 : clé refusée. 403 : modèle non accessible. 429 : limite de débit.", link: "https://console.anthropic.com/settings/keys" },
  { title: "Google Workspace", steps: ["Créez un projet Google Cloud.", "Configurez l’écran de consentement et ajoutez les scopes Gmail, Calendar et Drive.", "Créez un client OAuth Web.", "Ajoutez exactement l’URI /api/connections/google/callback de votre domaine.", "Copiez Client ID et Client Secret dans Connexions OAuth puis vérifiez."], errors: "invalid_client : mauvais ID/secret. redirect_uri_mismatch : URI différente caractère par caractère. access_denied : utilisateur non autorisé ou app en test.", link: "https://console.cloud.google.com/auth/clients" },
  { title: "Stripe", steps: ["Activez d’abord le mode Test dans Stripe.", "Copiez la clé publique et une clé secrète restreinte.", "Créez le webhook vers /api/billing/webhook.", "Abonnez checkout.session.completed et customer.subscription.*.", "Copiez whsec_ puis testez la connexion.", "Créez les Prices et associez leurs IDs aux offres."], errors: "No such price : mauvais Price ID. Signature invalide : mauvais whsec_. Clé live avec mode test : environnement incohérent.", link: "https://dashboard.stripe.com/apikeys" },
  { title: "Microsoft 365", steps: ["Ouvrez Microsoft Entra puis App registrations.", "Créez une application multitenant adaptée à un SaaS.", "Ajoutez la Redirect URI Web exacte de votre callback Astra.", "Créez un secret client et copiez sa valeur, pas son identifiant.", "Ajoutez les permissions Microsoft Graph nécessaires puis accordez le consentement administrateur."], errors: "AADSTS50011 : Redirect URI incorrecte. invalid_client : valeur du secret expirée ou mauvais tenant. Insufficient privileges : consentement administrateur absent.", link: "https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app" },
  { title: "GitHub", steps: ["Ouvrez Settings, Developer settings, OAuth Apps.", "Enregistrez une nouvelle OAuth App avec l’URL publique Astra.", "Ajoutez l’unique Authorization callback URL.", "Générez le Client Secret et stockez-le immédiatement dans Astra.", "Commencez avec read:user et user:email ; ajoutez repo uniquement si nécessaire."], errors: "redirect_uri_mismatch : callback différente. bad_verification_code : code expiré ou déjà utilisé. Les organisations SAML peuvent exiger une nouvelle autorisation.", link: "https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app" },
  { title: "Slack", steps: ["Créez une app depuis le portail Slack.", "Dans OAuth & Permissions, ajoutez la Redirect URL Astra.", "Choisissez des Bot Token Scopes minimaux, par exemple channels:read et chat:write.", "Copiez Client ID et Client Secret dans Astra.", "Installez l’application sur un workspace de test puis activez la rotation des tokens."], errors: "bad_redirect_uri : URL non déclarée. invalid_scope : permission indisponible. Un administrateur Slack peut devoir pré-approuver l’installation.", link: "https://docs.slack.dev/authentication/installing-with-oauth/" },
  { title: "Notion", steps: ["Créez une intégration publique Notion.", "Renseignez le domaine et la Redirect URI Astra.", "Copiez OAuth client ID et client secret.", "Sélectionnez uniquement les capacités de contenu requises.", "Soumettez l’intégration à validation avant une diffusion publique."], errors: "invalid_grant : code expiré. unauthorized : page non partagée avec l’intégration. Redirect URI et domaine doivent correspondre à la configuration publique.", link: "https://developers.notion.com/docs/authorization" },
  { title: "Discord", steps: ["Créez une application dans le Developer Portal.", "Dans OAuth2, ajoutez la Redirect URI Astra.", "Copiez Client ID puis réinitialisez et copiez le Client Secret.", "Choisissez identify, email ou guilds selon le besoin.", "Testez avec un compte autorisé avant d’ouvrir l’intégration."], errors: "invalid_client : identifiants incorrects. invalid_scope : scope non approuvé. Le token endpoint exige un corps application/x-www-form-urlencoded.", link: "https://docs.discord.com/developers/topics/oauth2" },
  { title: "Dropbox", steps: ["Créez une application dans l’App Console Dropbox.", "Choisissez l’accès App folder ou Full Dropbox selon le besoin réel.", "Ajoutez la Redirect URI HTTPS exacte.", "Activez les permissions minimales puis copiez App key et App secret.", "Utilisez un refresh token pour les connexions persistantes."], errors: "redirect_uri_mismatch : callback différente. invalid_access_token : jeton révoqué ou expiré. Une nouvelle permission nécessite une nouvelle autorisation utilisateur.", link: "https://developers.dropbox.com/oauth-guide" },
];

function DocumentationPanel() { return <div className="grid gap-4 lg:grid-cols-2">{docs.map((doc) => <Card key={doc.title}><CardHeader><CardTitle className="flex items-center justify-between gap-3"><span>{doc.title}</span><a href={doc.link} target="_blank" rel="noreferrer" className="text-xs font-normal text-primary">Portail officiel ↗</a></CardTitle></CardHeader><CardContent><ol className="space-y-2">{doc.steps.map((step, index) => <li key={step} className="flex gap-3 text-sm leading-6"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-primary/10 text-[11px] font-semibold text-primary">{index + 1}</span><span>{step}</span></li>)}</ol><div className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3"><p className="text-xs font-semibold text-amber-600">Erreurs fréquentes</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{doc.errors}</p></div></CardContent></Card>)}</div>; }

function MasterDetail({ title, description, items, selectedId, onSelect, onNew, children }: { title: string; description: string; items: Array<{ id: string; title: string; subtitle: string; status: VerificationStatusLike }>; selectedId: string; onSelect: (id: string) => void; onNew: () => void; children: React.ReactNode }) {
  return <div className="grid gap-5 lg:grid-cols-[300px_minmax(0,1fr)]"><Card className="h-fit"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{title}</CardTitle><p className="mt-2 text-xs leading-5 text-muted-foreground">{description}</p></div><Button size="icon" variant="outline" onClick={onNew} aria-label="Ajouter"><Plus className="size-4" /></Button></div></CardHeader><CardContent className="scrollbar-none flex gap-2 overflow-x-auto lg:block lg:max-h-[70vh] lg:space-y-2 lg:overflow-y-auto">{items.map((item) => <button key={item.id} onClick={() => onSelect(item.id)} className={`w-64 shrink-0 rounded-xl border p-3 text-left lg:w-full ${selectedId === item.id ? "border-primary bg-primary/5" : "hover:bg-muted/50"}`}><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-medium">{item.title}</p><StatusBadge status={item.status} /></div><p className="mt-1 truncate text-[11px] text-muted-foreground">{item.subtitle}</p></button>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">{selectedId === "new" ? "Nouvelle configuration" : "Modifier"}</CardTitle></CardHeader><CardContent>{children}</CardContent></Card></div>;
}

type VerificationStatusLike = "never" | "valid" | "invalid";
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-medium text-muted-foreground"><span className="mb-2 block">{label}</span>{children}</label>; }
function Check({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label className="flex cursor-pointer items-center gap-2 rounded-xl border p-3 text-xs"><input type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)} className="size-4 accent-primary" />{label}</label>; }
function splitList(value: string) { return value.split(/[,\n]/).map((item) => item.trim()).filter(Boolean); }
function numberOrUndefined(value: string) { const number = Number(value); return value === "" || !Number.isFinite(number) || number <= 0 ? undefined : Math.round(number); }
function NumberField({ label, name, form, setForm }: { label: string; name: string; form: Record<string, string | boolean>; setForm: (form: never) => void }) { return <Field label={label}><Input type="number" min="0" value={String(form[name] ?? "")} onChange={(event) => setForm({ ...form, [name]: event.target.value } as never)} /></Field>; }
