"use client";
import { useMemo, useState } from "react";
import { CheckCheck, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ApprovalCard } from "./approval-card";
import { useAppStore } from "@/stores/app-store";
export function ApprovalsPage() { const { approvals, resolveApproval } = useAppStore(); const [filter, setFilter] = useState("pending"); const visible = useMemo(() => approvals.filter((item) => filter === "all" || item.status === filter), [approvals, filter]); const resolve = (id: string, status: "approved" | "rejected") => { resolveApproval(id, status); toast.success(status === "approved" ? "Action autorisée et ajoutée à la file d’exécution" : "Action refusée et agent informé"); }; const approveLowRisk = () => { approvals.filter((item) => item.status === "pending" && item.risk === "low").forEach((item) => resolveApproval(item.id, "approved")); toast.success("Actions à faible risque autorisées"); }; return <div className="space-y-7"><PageHeader eyebrow="Contrôle humain" title="Centre de validations" description="Examinez les actions externes ou sensibles avant leur exécution, avec contexte, impact et traçabilité complète." actions={<Button variant="outline" onClick={approveLowRisk}><CheckCheck className="size-4" />Autoriser les faibles risques</Button>} /><div className="flex flex-wrap items-center gap-2">{[{ key: "pending", label: "En attente", count: approvals.filter((item) => item.status === "pending").length }, { key: "approved", label: "Autorisées", count: approvals.filter((item) => item.status === "approved").length }, { key: "rejected", label: "Refusées", count: approvals.filter((item) => item.status === "rejected").length }, { key: "all", label: "Toutes", count: approvals.length }].map((item) => <Button key={item.key} variant={filter === item.key ? "secondary" : "ghost"} size="sm" onClick={() => setFilter(item.key)}>{item.label}<Badge className="ml-1 bg-card text-muted-foreground">{item.count}</Badge></Button>)}</div><div className="space-y-4">{visible.length ? visible.map((approval) => <ApprovalCard key={approval.id} approval={approval} onResolve={(status) => resolve(approval.id, status)} />) : <div className="flex min-h-64 flex-col items-center justify-center rounded-2xl border border-dashed text-center"><ShieldCheck className="size-8 text-emerald-500" /><h2 className="mt-4 font-medium">Aucune validation dans cette vue</h2><p className="mt-1 text-sm text-muted-foreground">Les nouvelles demandes apparaîtront ici.</p></div>}</div></div>; }
