"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Bot, CalendarClock, CheckCircle2, ChevronRight, Clock3, FolderKanban, Gauge, Goal, Lightbulb, LoaderCircle, Play, ShieldCheck, Sparkles, TimerReset, Workflow, Zap } from "lucide-react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { useAppStore } from "@/stores/app-store";
import { AgentStatus, ConfidenceIndicator, RiskBadge } from "@/components/shared/indicators";
import { goalService } from "@/services";
import type { GoalAnalysis } from "@/types";

const chartData = ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"].map((day) => ({ day, value: 0 }));

export function DashboardPage() {
  const { goals, approvals, agents, activities, automations, account } = useAppStore();
  const [intent, setIntent] = useState("");
  const [analysis, setAnalysis] = useState<GoalAnalysis | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const analyze = async () => {
    if (intent.trim().length < 10) { toast.error("Décrivez votre objectif avec un peu plus de précision."); return; }
    setAnalyzing(true);
    setAnalysis(null);
    try {
      setAnalysis(await goalService.analyze(intent.trim()));
      toast.success("Objectif analysé par le Coordinateur");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Analyse impossible");
    } finally {
      setAnalyzing(false);
    }
  };
  const activeAgents = agents.filter((agent) => agent.status === "active").slice(0, 5);
  const completedTasks = goals.flatMap((goal) => goal.steps).flatMap((step) => step.tasks).filter((task) => task.status === "completed").length;
  const measuredAgents = agents.filter((agent) => agent.tasksCompleted > 0);
  const averageSuccessRate = measuredAgents.length ? Math.round(measuredAgents.reduce((total, agent) => total + agent.successRate, 0) / measuredAgents.length) : 0;
  const stats = [
    { label: "Objectifs actifs", value: String(goals.filter((goal) => goal.status === "active").length), delta: "Données réelles", icon: Goal, color: "text-indigo-500", bg: "bg-indigo-500/10" },
    { label: "Tâches terminées", value: String(completedTasks), delta: "Données réelles", icon: CheckCircle2, color: "text-emerald-500", bg: "bg-emerald-500/10" },
    { label: "Temps économisé", value: "0 h", delta: "Aucune mesure", icon: Clock3, color: "text-cyan-500", bg: "bg-cyan-500/10" },
    { label: "Automatisations", value: String(automations.filter((automation) => automation.status === "active").length), delta: "Données réelles", icon: Workflow, color: "text-violet-500", bg: "bg-violet-500/10" },
    { label: "Réussite agents", value: `${averageSuccessRate} %`, delta: measuredAgents.length ? "Données réelles" : "Aucune exécution", icon: Gauge, color: "text-amber-500", bg: "bg-amber-500/10" },
  ];
  const displayName = account?.fullName?.split(/\s+/)[0] || account?.email.split("@")[0] || "Utilisateur";
  const availableAgents = agents.filter((agent) => agent.enabled).length;
  return <div className="space-y-7">
    <section className="relative overflow-hidden rounded-3xl border bg-card p-6 md:p-8"><div className="pointer-events-none absolute inset-0 dot-grid opacity-60" /><div className="pointer-events-none absolute -right-24 -top-24 size-80 rounded-full bg-indigo-500/10 blur-3xl" /><div className="relative"><div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-3 flex items-center gap-2 text-sm text-muted-foreground"><span className="flex size-7 items-center justify-center rounded-lg bg-indigo-500/10 text-indigo-500"><Sparkles className="size-3.5" /></span>{availableAgents} agent{availableAgents > 1 ? "s" : ""} disponible{availableAgents > 1 ? "s" : ""}</div><h1 className="max-w-3xl text-3xl font-semibold tracking-tight md:text-4xl">Bonjour {displayName}, quel résultat voulez-vous obtenir ?</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Décrivez l’objectif. Astra analysera le contexte, construira un plan et coordonnera les bons agents sous votre contrôle.</p></div><div className="flex gap-3"><div className="rounded-2xl border bg-background/70 px-4 py-3"><p className="text-[10px] uppercase tracking-[.16em] text-muted-foreground">Agents disponibles</p><p className="mt-1 font-mono text-lg font-semibold">{availableAgents}</p></div><div className="rounded-2xl border bg-background/70 px-4 py-3"><p className="text-[10px] uppercase tracking-[.16em] text-muted-foreground">Décisions en attente</p><p className="mt-1 font-mono text-lg font-semibold text-amber-500">{approvals.filter((item) => item.status === "pending").length}</p></div></div></div>
      <div className="mt-7 rounded-2xl border bg-background/80 p-3 shadow-2xl shadow-indigo-500/5"><Textarea value={intent} onChange={(event) => { setIntent(event.target.value); setAnalysis(null); }} placeholder="Ex. Prépare le lancement de mon service d’automatisation pour les PME avant septembre." className="min-h-24 border-0 bg-transparent px-2 text-base focus:ring-0 md:text-lg" /><div className="flex flex-col gap-3 border-t px-2 pt-3 sm:flex-row sm:items-center"><div className="flex flex-1 flex-wrap gap-2"><Badge className="bg-muted text-muted-foreground"><FolderKanban className="size-3" />Contexte projet</Badge><Badge className="bg-muted text-muted-foreground"><ShieldCheck className="size-3" />Validation requise</Badge><Badge className="bg-muted text-muted-foreground"><Bot className="size-3" />Multi-agents</Badge></div><Button onClick={() => void analyze()} disabled={analyzing}>{analyzing ? <LoaderCircle className="size-4 animate-spin" /> : <Play className="size-4 fill-current" />}Comprendre l’objectif</Button></div></div>
      {analysis && <div className="mt-4 grid gap-3 rounded-2xl border border-indigo-500/30 bg-indigo-500/5 p-4 md:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 text-sm font-medium text-indigo-500"><CheckCircle2 className="size-4" />Intention comprise avec {analysis.confidence} % de confiance</div><p className="mt-2 text-sm text-muted-foreground">{analysis.summary}</p><div className="mt-3 flex flex-wrap gap-2">{analysis.dueDate && <Badge className="bg-card">Échéance · {new Date(analysis.dueDate).toLocaleDateString("fr-FR")}</Badge>}<Badge className="bg-card">{analysis.agentIds.length} agent(s) suggéré(s)</Badge><Badge className="bg-card">{analysis.steps.length} étapes principales</Badge><Badge className="bg-card">{analysis.model}</Badge></div></div><Link href={`/goals/new?intent=${encodeURIComponent(intent)}`} className="self-center"><Button variant="outline">Construire le plan<ArrowRight className="size-4" /></Button></Link></div>}
    </div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{stats.map((stat) => <Card key={stat.label}><CardContent className="p-4"><div className="flex items-start justify-between"><span className={`${stat.bg} ${stat.color} rounded-xl p-2.5`}><stat.icon className="size-4" /></span><span className="text-[10px] text-emerald-500">{stat.delta}</span></div><p className="mt-4 font-mono text-2xl font-semibold">{stat.value}</p><p className="mt-1 text-xs text-muted-foreground">{stat.label}</p></CardContent></Card>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Objectifs en cours</CardTitle><CardDescription>Progression synchronisée entre vos agents.</CardDescription></div><Link href="/goals"><Button variant="ghost" size="sm">Tout voir<ChevronRight className="size-4" /></Button></Link></CardHeader><CardContent className="space-y-3">{goals.filter((goal) => goal.status === "active").map((goal) => <Link key={goal.id} href={`/goals/${goal.id}`} className="block rounded-2xl border bg-background p-4 transition hover:border-indigo-500/40"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-indigo-500" /><h3 className="truncate font-medium">{goal.title}</h3></div><p className="mt-1 truncate text-xs text-muted-foreground">Échéance {new Date(goal.dueDate).toLocaleDateString("fr-FR", { day: "numeric", month: "long" })} · Autonomie N{goal.autonomyLevel}</p></div><span className="font-mono text-sm font-semibold">{goal.progress}%</span></div><Progress value={goal.progress} className="mt-4" /><div className="mt-3 flex items-center justify-between"><div className="flex -space-x-2">{goal.agentIds.slice(0, 5).map((id) => <span key={id} className="flex size-7 items-center justify-center rounded-full border-2 border-card bg-muted text-[9px] font-semibold uppercase">{id.slice(0, 2)}</span>)}</div><span className="text-xs text-muted-foreground">Prochaine action : validation</span></div></Link>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Productivité augmentée</CardTitle><CardDescription>Heures réellement mesurées après exécution.</CardDescription></CardHeader><CardContent><div className="flex items-end justify-between"><div><p className="font-mono text-3xl font-semibold">0 h</p><p className="mt-1 text-xs text-muted-foreground">Aucune mesure disponible</p></div><TimerReset className="size-8 text-cyan-500" /></div><div className="mt-5 h-36"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="productivity" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6366f1" stopOpacity={0.5} /><stop offset="100%" stopColor="#6366f1" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#8f99aa" }} /><Tooltip contentStyle={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 12, fontSize: 12 }} /><Area type="monotone" dataKey="value" stroke="#6366f1" strokeWidth={2} fill="url(#productivity)" /></AreaChart></ResponsiveContainer></div></CardContent></Card></section>
    <section className="grid gap-5 xl:grid-cols-3"><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Validations requises</CardTitle><CardDescription>Décisions qui restent sous votre contrôle.</CardDescription></div><Link href="/approvals"><Badge className="border-amber-500/20 bg-amber-500/10 text-amber-500">{approvals.filter((item) => item.status === "pending").length} en attente</Badge></Link></CardHeader><CardContent className="space-y-3">{approvals.filter((item) => item.status === "pending").slice(0, 2).map((approval) => <div key={approval.id} className="rounded-xl border bg-background p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{approval.action}</p><p className="mt-1 text-xs text-muted-foreground">Demandé par {approval.agent}</p></div><RiskBadge risk={approval.risk} /></div></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Agents actifs</CardTitle><CardDescription>Travail en cours dans votre espace.</CardDescription></CardHeader><CardContent className="space-y-3">{activeAgents.map((agent) => <Link key={agent.id} href={`/agents/${agent.id}`} className="flex items-center gap-3 rounded-xl p-2 hover:bg-muted"><span className="flex size-9 items-center justify-center rounded-xl bg-indigo-500/10 text-indigo-500"><Bot className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{agent.name}</p><AgentStatus status={agent.status} label={agent.lastActivity} /></div><ConfidenceIndicator value={agent.successRate} compact /></Link>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Automatisations proposées</CardTitle><CardDescription>Opportunités détectées dans votre routine.</CardDescription></CardHeader><CardContent className="space-y-3">{automations.filter((item) => item.status === "suggested").map((automation) => <div key={automation.id} className="rounded-xl border bg-background p-4"><span className="mb-3 inline-flex rounded-lg bg-violet-500/10 p-2 text-violet-500"><Lightbulb className="size-4" /></span><p className="text-sm font-medium">{automation.name}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{automation.description}</p><Link href="/automations"><Button variant="outline" size="sm" className="mt-3">Examiner<ArrowRight className="size-3" /></Button></Link></div>)}</CardContent></Card></section>
    <section className="grid gap-5 lg:grid-cols-[1fr_.75fr]"><Card><CardHeader><CardTitle>Activité récente</CardTitle><CardDescription>Un journal transparent de l’exécution numérique.</CardDescription></CardHeader><CardContent className="space-y-1">{activities.slice(0, 4).map((event) => <div key={event.id} className="flex items-center gap-3 border-b py-3 last:border-0"><span className="flex size-8 items-center justify-center rounded-lg bg-muted"><Zap className="size-3.5 text-indigo-500" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm">{event.action}</p><p className="text-[11px] text-muted-foreground">{event.agent} · {event.timestamp}</p></div><ConfidenceIndicator value={event.confidence} compact /></div>)}</CardContent></Card><Card><CardHeader><CardTitle>À venir</CardTitle><CardDescription>Échéances et événements préparés par Astra.</CardDescription></CardHeader><CardContent className="space-y-3">{[{ date: "18 JUIL.", title: "Validation finale de l’offre", meta: "Objectif principal" }, { date: "22 JUIL.", title: "Démonstration avec Maison Vela", meta: "Google Calendar · 14:30" }, { date: "31 JUIL.", title: "Site prêt pour révision", meta: "Développement" }].map((item) => <div key={item.title} className="flex gap-3 rounded-xl border bg-background p-3"><div className="flex w-14 shrink-0 flex-col items-center justify-center rounded-lg bg-muted font-mono text-[10px] font-semibold text-indigo-500">{item.date}</div><div><p className="text-sm font-medium">{item.title}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><CalendarClock className="size-3" />{item.meta}</p></div></div>)}</CardContent></Card></section>
  </div>;
}
