"use client";
import { useState } from "react";
import { Bell, BrainCircuit, Check, ChevronRight, Coins, Database, Eye, LockKeyhole, Palette, Save, ShieldCheck, SlidersHorizontal, UserRound } from "lucide-react";
import { toast } from "sonner";
import { useTheme } from "@/components/layout/theme-provider";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { autonomyLevels, models, sensitiveActions } from "@/config";
import { useAppStore } from "@/stores/app-store";
import { cn } from "@/lib/utils";
const sections = [{ key: "profile", label: "Profil", icon: UserRound }, { key: "appearance", label: "Apparence", icon: Palette }, { key: "models", label: "Modèles IA", icon: SlidersHorizontal }, { key: "autonomy", label: "Autonomie", icon: ShieldCheck }, { key: "permissions", label: "Permissions", icon: LockKeyhole }, { key: "privacy", label: "Confidentialité", icon: Eye }, { key: "memory", label: "Mémoire", icon: BrainCircuit }, { key: "security", label: "Sécurité", icon: LockKeyhole }, { key: "budget", label: "Budget", icon: Coins }, { key: "notifications", label: "Notifications", icon: Bell }, { key: "data", label: "Données", icon: Database }];
const actions = ["Lire", "Créer", "Modifier", "Supprimer", "Envoyer", "Publier", "Acheter", "Planifier"];
export function SettingsPage() { const [section, setSection] = useState("autonomy"); const [autonomy, setAutonomy] = useState(2); const { theme, setTheme } = useTheme(); const agents = useAppStore((state) => state.agents).slice(0, 6); return <div className="space-y-7"><PageHeader eyebrow="Gouvernance" title="Paramètres et permissions" description="Définissez les limites d’exécution, les modèles, la confidentialité et les budgets de votre système." actions={<Button onClick={() => toast.success("Paramètres enregistrés")}><Save className="size-4" />Enregistrer</Button>} /><div className="grid gap-5 lg:grid-cols-[220px_1fr]"><Card className="h-fit"><CardContent className="p-2">{sections.map((item) => <button key={item.key} onClick={() => setSection(item.key)} className={cn("flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm", section === item.key ? "bg-accent text-accent-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground")}><item.icon className="size-4" />{item.label}<ChevronRight className="ml-auto size-3" /></button>)}</CardContent></Card><div className="space-y-5">{section === "autonomy" && <><Card><CardHeader><CardTitle>Niveau d’autonomie par défaut</CardTitle></CardHeader><CardContent className="space-y-2">{autonomyLevels.map((item) => <button key={item.level} onClick={() => setAutonomy(item.level)} className={cn("flex w-full items-center gap-4 rounded-xl border p-4 text-left", autonomy === item.level ? "border-indigo-500 bg-indigo-500/5" : "bg-background")}><span className={cn("flex size-10 items-center justify-center rounded-xl font-mono text-sm", autonomy === item.level ? "bg-indigo-500 text-white" : "bg-muted")}>N{item.level}</span><div className="flex-1"><p className="text-sm font-medium">{item.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.description}</p></div>{autonomy === item.level && <Check className="size-4 text-indigo-500" />}</button>)}</CardContent></Card><Card className="border-amber-500/20"><CardHeader><CardTitle className="text-base">Validation toujours obligatoire</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Ces actions restent bloquées jusqu’à une décision humaine, même au niveau 4.</p><div className="mt-4 flex flex-wrap gap-2">{sensitiveActions.map((action) => <Badge key={action} className="bg-amber-500/10 text-amber-500">{action}</Badge>)}</div></CardContent></Card></>}
        {section === "permissions" && <Card><CardHeader><CardTitle>Matrice de permissions</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-4 text-left">Agent</th>{actions.map((action) => <th key={action} className="px-2 text-center text-[10px] font-medium text-muted-foreground">{action}</th>)}</tr></thead><tbody>{agents.map((agent, row) => <tr key={agent.id} className="border-b last:border-0"><td className="p-4 font-medium">{agent.name}</td>{actions.map((action, column) => <td key={action} className="p-2 text-center"><input type="checkbox" defaultChecked={column < 3 || (row === 0 && column === 7)} aria-label={`${agent.name} peut ${action.toLowerCase()}`} className="size-4 accent-indigo-500" /></td>)}</tr>)}</tbody></table></CardContent></Card>}
        {section === "appearance" && <Card><CardHeader><CardTitle>Apparence</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-3">{["light", "dark", "system"].map((item) => <button key={item} onClick={() => setTheme(item)} className={cn("rounded-xl border p-5 text-left capitalize", theme === item && "border-indigo-500 bg-indigo-500/5")}><Palette className="size-5 text-indigo-500" /><p className="mt-4 font-medium">{item === "light" ? "Clair" : item === "dark" ? "Sombre" : "Système"}</p></button>)}</div></CardContent></Card>}
        {section === "models" && <Card><CardHeader><CardTitle>Modèles IA</CardTitle></CardHeader><CardContent className="space-y-3">{models.map((model) => <div key={model.id} className="flex items-center gap-4 rounded-xl border bg-background p-4"><div className="flex-1"><div className="flex items-center gap-2"><p className="font-medium">{model.name}</p><Badge className="bg-muted text-muted-foreground">{model.provider}</Badge></div><p className="mt-1 text-xs text-muted-foreground">Fenêtre de contexte : {model.contextWindow}</p></div><Switch checked={model.enabled} onCheckedChange={() => toast.info("Configuration simulée")} label={`Activer ${model.name}`} /></div>)}</CardContent></Card>}
        {!["autonomy", "permissions", "appearance", "models"].includes(section) && <Card><CardHeader><CardTitle>{sections.find((item) => item.key === section)?.label}</CardTitle></CardHeader><CardContent className="space-y-4"><label className="text-sm font-medium">Nom de l’espace<Input defaultValue="Espace Pro de Paul" className="mt-2" /></label><div className="flex items-center justify-between rounded-xl border bg-background p-4"><div><p className="text-sm font-medium">Journalisation renforcée</p><p className="text-xs text-muted-foreground">Conserver les traces techniques pendant 90 jours.</p></div><Switch checked onCheckedChange={() => toast.info("Préférence simulée")} label="Journalisation renforcée" /></div><div className="flex items-center justify-between rounded-xl border bg-background p-4"><div><p className="text-sm font-medium">Notifications importantes</p><p className="text-xs text-muted-foreground">Recevoir les validations et erreurs critiques.</p></div><Switch checked onCheckedChange={() => toast.info("Préférence simulée")} label="Notifications importantes" /></div></CardContent></Card>}</div></div></div>; }
