"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ArrowLeft, ArrowRight, Bot, CalendarDays, Check, CheckCircle2, Database, LoaderCircle, Pencil, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/input";
import { autonomyLevels } from "@/config";
import { cn } from "@/lib/utils";
import { useAppStore } from "@/stores/app-store";
import { ExecutionTimeline } from "@/components/shared/execution-timeline";
import { goals as mockGoals } from "@/mocks/data";
import type { AutonomyLevel, Goal } from "@/types";

const schema = z.object({ intent: z.string().min(15, "Décrivez un résultat attendu en au moins 15 caractères.") });
type FormData = z.infer<typeof schema>;
const steps = ["Objectif", "Contexte", "Questions", "Plan", "Autonomie", "Confirmation"];

export function GoalWizard() {
  const router = useRouter();
  const addGoal = useAppStore((state) => state.addGoal);
  const [step, setStep] = useState(0);
  const [processing, setProcessing] = useState(false);
  const [autonomy, setAutonomy] = useState<AutonomyLevel>(2);
  const [plan, setPlan] = useState(mockGoals[0].steps);
  const { register, getValues, setValue, trigger, formState: { errors } } = useForm<FormData>({ resolver: zodResolver(schema), defaultValues: { intent: "Prépare le lancement de mon service d’automatisation pour les PME avant septembre." } });
  useEffect(() => { const intent = new URLSearchParams(window.location.search).get("intent"); if (intent) setValue("intent", intent); }, [setValue]);
  const next = async () => { if (step === 0 && !(await trigger())) return; if (step < 5) { setProcessing(true); setTimeout(() => { setProcessing(false); setStep((current) => current + 1); }, step < 3 ? 500 : 200); } };
  const create = () => { const goal: Goal = { ...mockGoals[0], id: `goal-${Date.now()}`, title: getValues("intent").replace(/[.!?]$/, ""), description: "Objectif créé depuis l’assistant de planification Astra.", progress: 0, createdAt: new Date().toISOString(), autonomyLevel: autonomy, steps: plan.map((item) => ({ ...item, status: "pending" })) }; addGoal(goal); toast.success("Objectif créé — le Coordinateur prépare l’exécution"); router.push(`/goals/${goal.id}`); };
  return <div className="mx-auto max-w-5xl space-y-6"><div><Button variant="ghost" size="sm" onClick={() => router.back()}><ArrowLeft className="size-4" />Retour</Button><h1 className="mt-4 text-3xl font-semibold tracking-tight">Transformer une idée en résultat</h1><p className="mt-2 text-sm text-muted-foreground">Le Coordinateur structure votre intention avant toute exécution.</p></div><div className="scrollbar-none flex overflow-x-auto rounded-2xl border bg-card p-2">{steps.map((label, index) => <div key={label} className={cn("flex min-w-[140px] flex-1 items-center gap-2 rounded-xl px-3 py-2 text-xs", index === step && "bg-accent text-accent-foreground", index < step && "text-emerald-500", index > step && "text-muted-foreground")}><span className={cn("flex size-6 items-center justify-center rounded-full border font-mono text-[10px]", index < step && "border-emerald-500 bg-emerald-500 text-white", index === step && "border-indigo-500 text-indigo-500")}>{index < step ? <Check className="size-3" /> : index + 1}</span>{label}</div>)}</div>
    <Card className="min-h-[500px]"><CardContent className="p-6 md:p-8">{processing ? <div className="flex min-h-[420px] flex-col items-center justify-center text-center"><span className="relative flex size-16 items-center justify-center rounded-2xl bg-indigo-500/10 text-indigo-500"><LoaderCircle className="size-7 animate-spin" /></span><h2 className="mt-5 font-semibold">Analyse du contexte en cours</h2><p className="mt-2 max-w-md text-sm text-muted-foreground">Le Coordinateur rapproche votre intention des projets, connexions et habitudes disponibles.</p></div> : <>
      {step === 0 && <section><span className="inline-flex rounded-xl bg-indigo-500/10 p-3 text-indigo-500"><Sparkles className="size-5" /></span><h2 className="mt-5 text-xl font-semibold">Quel résultat voulez-vous obtenir ?</h2><p className="mt-2 text-sm text-muted-foreground">Formulez un résultat concret, une échéance et les contraintes importantes.</p><Textarea {...register("intent")} className="mt-6 min-h-40 text-base" />{errors.intent && <p className="mt-2 text-xs text-rose-500">{errors.intent.message}</p>}<div className="mt-4 rounded-xl border bg-muted/40 p-4 text-xs text-muted-foreground">Conseil : préférez « Lancer mon offre avant septembre avec 10 prospects qualifiés » à « Travailler sur mon offre ».</div></section>}
      {step === 1 && <section><span className="inline-flex rounded-xl bg-cyan-500/10 p-3 text-cyan-500"><Database className="size-5" /></span><h2 className="mt-5 text-xl font-semibold">Contexte détecté</h2><p className="mt-2 text-sm text-muted-foreground">Ces éléments seront utilisés pour construire le plan. Rien ne sera transmis sans permission.</p><div className="mt-6 grid gap-3 md:grid-cols-2">{[{ icon: "FolderKanban", title: "Projet lié", value: "Service d’automatisation PME" }, { icon: "FileText", title: "Documents", value: "8 documents commerciaux" }, { icon: "Users", title: "Personnes", value: "Paul Martin, Léa Martin" }, { icon: "Plug", title: "Connexions", value: "Gmail, Drive, GitHub, Notion" }].map((item) => <div key={item.title} className="rounded-xl border bg-background p-4"><p className="text-xs text-muted-foreground">{item.title}</p><p className="mt-1 text-sm font-medium">{item.value}</p></div>)}</div><div className="mt-5 flex items-start gap-3 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4"><ShieldCheck className="mt-0.5 size-4 text-emerald-500" /><p className="text-sm"><strong>Contrôle des données.</strong> L’agent utilisera uniquement les sources sélectionnées et journalisera chaque accès.</p></div></section>}
      {step === 2 && <section><span className="inline-flex rounded-xl bg-amber-500/10 p-3 text-amber-500"><CalendarDays className="size-5" /></span><h2 className="mt-5 text-xl font-semibold">Deux précisions amélioreraient le plan</h2><p className="mt-2 text-sm text-muted-foreground">Vous pouvez accepter les hypothèses proposées.</p><div className="mt-6 space-y-4">{[{ q: "Quelle est l’échéance exacte ?", a: "31 août 2026" }, { q: "Quel segment doit être prioritaire ?", a: "Cabinets de services de 10 à 50 salariés" }].map((item) => <label key={item.q} className="block rounded-xl border bg-background p-4"><span className="text-sm font-medium">{item.q}</span><input defaultValue={item.a} className="mt-3 h-10 w-full rounded-lg border bg-card px-3 text-sm" /></label>)}</div></section>}
      {step === 3 && <section><div className="flex items-start justify-between"><div><span className="inline-flex rounded-xl bg-violet-500/10 p-3 text-violet-500"><Wrench className="size-5" /></span><h2 className="mt-5 text-xl font-semibold">Plan d’exécution proposé</h2><p className="mt-2 text-sm text-muted-foreground">4 étapes, 6 sous-tâches et 5 agents coordonnés.</p></div><Button variant="outline" size="sm" onClick={() => { setPlan((items) => items.map((item, index) => index === 0 ? { ...item, title: item.title === "Définir l’offre" ? "Cadrer l’offre et le positionnement" : "Définir l’offre" } : item)); toast.success("Première étape modifiée"); }}><Pencil className="size-3" />Modifier</Button></div><div className="mt-6"><ExecutionTimeline steps={plan} /></div></section>}
      {step === 4 && <section><span className="inline-flex rounded-xl bg-emerald-500/10 p-3 text-emerald-500"><Bot className="size-5" /></span><h2 className="mt-5 text-xl font-semibold">Quel niveau d’autonomie accordez-vous ?</h2><p className="mt-2 text-sm text-muted-foreground">Les actions sensibles demanderont toujours une validation, quel que soit le niveau choisi.</p><div className="mt-6 space-y-2">{autonomyLevels.map((item) => <button key={item.level} onClick={() => setAutonomy(item.level)} className={cn("flex w-full items-center gap-4 rounded-xl border p-4 text-left transition", autonomy === item.level ? "border-indigo-500 bg-indigo-500/5" : "bg-background hover:bg-muted/40")}><span className={cn("flex size-9 items-center justify-center rounded-xl font-mono text-sm", autonomy === item.level ? "bg-indigo-500 text-white" : "bg-muted")}>N{item.level}</span><div className="flex-1"><p className="text-sm font-medium">{item.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.description}</p></div>{autonomy === item.level && <CheckCircle2 className="size-5 text-indigo-500" />}</button>)}</div></section>}
      {step === 5 && <section className="text-center"><span className="inline-flex rounded-2xl bg-emerald-500/10 p-4 text-emerald-500"><CheckCircle2 className="size-7" /></span><h2 className="mt-5 text-2xl font-semibold">Tout est prêt pour l’exécution</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Le Coordinateur créera l’objectif, attribuera les premières tâches et vous demandera une validation avant chaque action externe sensible.</p><div className="mx-auto mt-7 grid max-w-2xl gap-3 text-left sm:grid-cols-3"><div className="rounded-xl border bg-background p-4"><p className="text-xs text-muted-foreground">Plan</p><p className="mt-1 font-medium">4 étapes</p></div><div className="rounded-xl border bg-background p-4"><p className="text-xs text-muted-foreground">Agents</p><p className="mt-1 font-medium">5 coordonnés</p></div><div className="rounded-xl border bg-background p-4"><p className="text-xs text-muted-foreground">Autonomie</p><p className="mt-1 font-medium">Niveau {autonomy}</p></div></div><Button size="lg" className="mt-8" onClick={create}><Sparkles className="size-4" />Créer et démarrer l’objectif</Button></section>}
    </>}</CardContent></Card>
    {step < 5 && <div className="flex items-center justify-between"><Button variant="ghost" disabled={step === 0} onClick={() => setStep((current) => current - 1)}><ArrowLeft className="size-4" />Précédent</Button><Button onClick={() => void next()}>Continuer<ArrowRight className="size-4" /></Button></div>}</div>;
}
