"use client";
import { useState } from "react";
import { notFound } from "next/navigation";
import { Bot, CalendarDays, CheckCircle2, History, MoreHorizontal, RotateCcw, Settings2, ShieldCheck, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { useAppStore } from "@/stores/app-store";
import { ExecutionTimeline } from "@/components/shared/execution-timeline";
import { ConfidenceIndicator } from "@/components/shared/indicators";
import { cn } from "@/lib/utils";
const tabs = ["Vue d’ensemble", "Plan", "Tâches", "Activité", "Documents", "Mémoire", "Décisions", "Paramètres"];
export function GoalDetailPage({ id }: { id: string }) { const goal = useAppStore((state) => state.goals.find((item) => item.id === id)); const agents = useAppStore((state) => state.agents); const [tab, setTab] = useState("Vue d’ensemble"); if (!goal) return notFound(); const goalAgents = agents.filter((agent) => goal.agentIds.includes(agent.id)); return <div className="space-y-6"><section className="rounded-3xl border bg-card p-6 md:p-8"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div className="max-w-3xl"><div className="flex flex-wrap gap-2"><Badge className="border-indigo-500/20 bg-indigo-500/10 text-indigo-500">Objectif actif</Badge><Badge className="bg-muted text-muted-foreground">Priorité {goal.priority}</Badge><Badge className="bg-muted text-muted-foreground">Autonomie N{goal.autonomyLevel}</Badge></div><h1 className="mt-4 text-2xl font-semibold tracking-tight md:text-3xl">{goal.title}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{goal.description}</p></div><div className="flex gap-2"><Button variant="outline"><Settings2 className="size-4" />Configurer</Button><Button variant="ghost" size="icon"><MoreHorizontal className="size-4" /></Button></div></div><div className="mt-7 grid gap-4 md:grid-cols-[1fr_auto]"><div><div className="flex items-center justify-between text-xs"><span>Progression globale</span><span className="font-mono font-semibold">{goal.progress}%</span></div><Progress value={goal.progress} className="mt-2 h-2" /></div><div className="flex gap-6 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><CalendarDays className="size-4" />{new Date(goal.dueDate).toLocaleDateString("fr-FR")}</span><span className="flex items-center gap-1.5"><Bot className="size-4" />{goalAgents.length} agents</span></div></div></section>
    <div className="scrollbar-none flex overflow-x-auto border-b">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={cn("whitespace-nowrap border-b-2 px-4 py-3 text-sm", tab === item ? "border-indigo-500 text-foreground" : "border-transparent text-muted-foreground hover:text-foreground")}>{item}</button>)}</div>
    {tab === "Vue d’ensemble" && <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><Card><CardHeader><CardTitle>État d’exécution</CardTitle></CardHeader><CardContent><ExecutionTimeline steps={goal.steps.length ? goal.steps : mockFallbackSteps} /></CardContent></Card><div className="space-y-5"><Card><CardHeader><CardTitle>Agents impliqués</CardTitle></CardHeader><CardContent className="space-y-3">{goalAgents.map((agent) => <div key={agent.id} className="flex items-center gap-3 rounded-xl border bg-background p-3"><span className="rounded-lg bg-indigo-500/10 p-2 text-indigo-500"><Bot className="size-4" /></span><div className="flex-1"><p className="text-sm font-medium">{agent.name}</p><p className="text-xs text-muted-foreground">{agent.role}</p></div><ConfidenceIndicator value={agent.successRate} compact /></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Résumé de contrôle</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div className="flex items-center gap-3"><ShieldCheck className="size-4 text-emerald-500" /><span>Validation obligatoire pour les actions externes</span></div><div className="flex items-center gap-3"><History className="size-4 text-indigo-500" /><span>Journalisation complète activée</span></div><div className="flex items-center gap-3"><RotateCcw className="size-4 text-cyan-500" /><span>7 actions réversibles</span></div></CardContent></Card></div></div>}
    {tab === "Plan" && <Card><CardHeader><CardTitle>Plan et dépendances</CardTitle></CardHeader><CardContent><ExecutionTimeline steps={goal.steps.length ? goal.steps : mockFallbackSteps} /></CardContent></Card>}
    {tab === "Décisions" && <Card><CardHeader><CardTitle>Historique des décisions</CardTitle></CardHeader><CardContent className="space-y-3">{goal.decisions.length ? goal.decisions.map((decision) => <div key={decision.id} className="rounded-xl border bg-background p-4"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><CheckCircle2 className="size-4 text-emerald-500" /><h3 className="font-medium">{decision.title}</h3></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{decision.rationale}</p><div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground"><span>{decision.agent}</span><span>{decision.model}</span><span>{new Date(decision.date).toLocaleString("fr-FR")}</span></div></div><ConfidenceIndicator value={decision.confidence} /></div><div className="mt-4 flex gap-2 border-t pt-3"><Button variant="outline" size="sm" onClick={() => toast.success("Décision marquée pour réexamen")}><RotateCcw className="size-3" />Réexaminer</Button>{decision.reversible && <Button variant="ghost" size="sm">Annuler</Button>}</div></div>) : <p className="py-12 text-center text-sm text-muted-foreground">Aucune décision n’a encore été enregistrée.</p>}</CardContent></Card>}
    {!["Vue d’ensemble", "Plan", "Décisions"].includes(tab) && <Card><CardContent className="flex min-h-64 flex-col items-center justify-center text-center"><span className="rounded-xl bg-muted p-3"><Sparkles className="size-5 text-indigo-500" /></span><h3 className="mt-4 font-medium">{tab}</h3><p className="mt-1 text-sm text-muted-foreground">Cette vue est prête à recevoir les données de votre backend.</p></CardContent></Card>}
  </div>; }
const mockFallbackSteps = [{ id: "fallback", title: "Plan en préparation", description: "Le Coordinateur structure les premières étapes.", status: "active" as const, dueDate: "À définir", agentIds: ["coordinateur"], toolIds: [], risk: "low" as const, confidence: 88, tasks: [] }];
